in send.rb, when response["errors"] is not null, use "messages =" instead of "messages +=", otherwise, below error would happen: ./send.rb:61: undefined method `+' for nil:NilClass (NoMethodError)